from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class Message(BaseModel):
    role: str = Field(
        ...,
        description="The role of the message sender (e.g. 'system', 'user', 'assistant', 'tool')",
    )
    content: str = Field(..., description="The text content of the message")
    name: Optional[str] = Field(
        None,
        description="Optional name of the sender, required for tool replies",
    )


class ChatRequest(BaseModel):
    messages: List[Message] = Field(
        ..., description="The sequence of conversation messages so far"
    )
    stream: bool = Field(
        default=False, description="Whether to stream the response incrementally"
    )
    config: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional runtime configurations (e.g. thread_id for checkpointers)",
    )


class ChatResponse(BaseModel):
    message: Message = Field(
        ..., description="The final reply generated by the agent workflow"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Key-value metrics or traces from agent execution steps",
    )
